# Generated by Django 4.0.1 on 2022-01-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='level',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
