# Generated by Django 4.0.1 on 2022-01-07 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('rateperhour', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
