# Generated by Django 4.0.1 on 2022-01-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignments',
        ),
    ]
