# Generated by Django 4.0.1 on 2022-01-12 11:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutors',
            name='levels',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Pre-U/JC', 'Pre-U/JC')], max_length=26),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='locations',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Central', 'Central'), ('East', 'East'), ('North', 'North'), ('Northeast', 'Northeast'), ('West', 'West')], max_length=33),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Quran', 'Quran'), ('Arabic', 'Arabic'), ('Malay', 'Malay'), ('English', 'English'), ('Maths', 'Maths'), ('Science', 'Science'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Ukhrawi Subjects', 'Ukhrawi Subjects'), ('E-Maths', 'E-Maths'), ('A-Maths', 'A-Maths')], max_length=99),
        ),
    ]
