# Generated by Django 4.0.1 on 2022-01-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_tutors_levels_alter_tutors_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutors',
            name='is_ars',
            field=models.BooleanField(default=True),
        ),
    ]
