# Generated by Django 4.0.1 on 2022-01-25 11:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_tutors_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endorsers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, size=None)),
                ('target', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.tutors')),
            ],
        ),
    ]
